version: '3.8'
services:
  db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  api:
    container_name: bricks-core
    build:
      context: ./
      target: production
    image: bricks-core
    depends_on:
      - db
    ports:
      - "9000:8080"
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local